name: CI

on:
  push:
    branches-ignore:
      - "renovate/**"

jobs:
  prepare:
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14.x, 16.x]

    runs-on: ${{ matrix.os }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache ~/.pnpm-store
        uses: actions/cache@v2
        env:
          cache-name: cache-pnpm-store
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ matrix.node-version }}-test-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.node-version }}-test-${{ env.cache-name }}-
            ${{ runner.os }}-${{ matrix.node-version }}-test-
            ${{ runner.os }}-
      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm i

      - name: All tasks
        run: pnpm all

  ui-chrome-tests:
    runs-on: ubuntu-latest
    container: cypress/browsers:node12.18.3-chrome87-ff82
    needs: prepare
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Install pnpm
        run: npm i -g pnpm

      - name: Install deps
        run: pnpm i

      - name: "UI Tests - Chrome"
        uses: cypress-io/github-action@v4
        with:
          # we have already installed all dependencies above
          install: false
          start: pnpm e2e:app
          wait-on: "http://127.0.0.1:5173/"
          wait-on-timeout: 120
          browser: chrome
          record: false
          parallel: true
          group: "UI - Chrome"
          spec: packages/app/cypress/e2e/*.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# release:
#   runs-on: ubuntu-latest
#   needs: ['test']
#   if: "!contains(github.event.head_commit.message, 'skip-release') && !contains(github.event.head_commit.message, 'skip-ci') && github.event_name != 'pull_request'"
#   steps:
#     - uses: actions/checkout@v2
#     - uses: actions/setup-node@v2
#       with:
#         node-version: 14.x
#     - name: Cache ~/.pnpm-store
#       uses: actions/cache@v2
#       env:
#         cache-name: cache-pnpm-store
#       with:
#         path: ~/.pnpm-store
#         key: ${{ runner.os }}-${{ matrix.node-version }}-release-${{ env.cache-name }}-${{ hashFiles('**/pnpm-lock.yaml') }}
#         restore-keys: |
#           ${{ runner.os }}-${{ matrix.node-version }}-release-${{ env.cache-name }}-
#           ${{ runner.os }}-${{ matrix.node-version }}-release-
#           ${{ runner.os }}-
#     - run: npm i -g pnpm
#     - run: pnpm i
#     - run: pnpx semantic-release --branches main
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
